// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "99minutos Engineering",
            "url": "https://99minutos.com"
        },
        "license": {
            "name": "MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.loginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.authResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Register a new user",
                "parameters": [
                    {
                        "description": "User registration details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.registerRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/handler.authResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Liveness probe",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/health/ready": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Readiness probe",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.readinessResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/handler.readinessResponse"
                        }
                    }
                }
            }
        },
        "/v1/shipments": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "shipments"
                ],
                "summary": "List shipments",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by status (created, picked_up, in_warehouse, in_transit, delivered, cancelled)",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by service type (same_day, next_day, standard)",
                        "name": "service_type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Partial match on tracking_number or sender name",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Created at \u003e= date (YYYY-MM-DD)",
                        "name": "date_from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Created at \u003c= date (YYYY-MM-DD)",
                        "name": "date_to",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number (default 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Items per page (default 20, max 100)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.listShipmentsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "shipments"
                ],
                "summary": "Create a new shipment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Idempotency key to prevent duplicate submissions",
                        "name": "Idempotency-Key",
                        "in": "header"
                    },
                    {
                        "description": "Shipment details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.createShipmentRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/handler.createShipmentResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/v1/shipments/{tracking_number}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "shipments"
                ],
                "summary": "Get a shipment by tracking number",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tracking number (e.g. 99M-7A8B9C2D)",
                        "name": "tracking_number",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.getShipmentResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handler.addressRequest": {
            "type": "object",
            "required": [
                "address",
                "city",
                "coordinates",
                "zip_code"
            ],
            "properties": {
                "address": {
                    "type": "string"
                },
                "city": {
                    "type": "string"
                },
                "coordinates": {
                    "$ref": "#/definitions/handler.coordinatesRequest"
                },
                "zip_code": {
                    "type": "string"
                }
            }
        },
        "handler.addressResponse": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "city": {
                    "type": "string"
                },
                "coordinates": {
                    "$ref": "#/definitions/handler.coordinatesResponse"
                },
                "zip_code": {
                    "type": "string"
                }
            }
        },
        "handler.authResponse": {
            "type": "object",
            "properties": {
                "expires_in": {
                    "type": "integer"
                },
                "token": {
                    "type": "string"
                },
                "token_type": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/handler.userPayload"
                }
            }
        },
        "handler.coordinatesRequest": {
            "type": "object",
            "required": [
                "lat",
                "lng"
            ],
            "properties": {
                "lat": {
                    "type": "number"
                },
                "lng": {
                    "type": "number"
                }
            }
        },
        "handler.coordinatesResponse": {
            "type": "object",
            "properties": {
                "lat": {
                    "type": "number"
                },
                "lng": {
                    "type": "number"
                }
            }
        },
        "handler.createShipmentRequest": {
            "type": "object",
            "required": [
                "destination",
                "origin",
                "package",
                "sender",
                "service_type"
            ],
            "properties": {
                "destination": {
                    "$ref": "#/definitions/handler.addressRequest"
                },
                "origin": {
                    "$ref": "#/definitions/handler.addressRequest"
                },
                "package": {
                    "$ref": "#/definitions/handler.packageRequest"
                },
                "sender": {
                    "$ref": "#/definitions/handler.senderRequest"
                },
                "service_type": {
                    "type": "string",
                    "enum": [
                        "same_day",
                        "next_day",
                        "standard"
                    ]
                }
            }
        },
        "handler.createShipmentResponse": {
            "type": "object",
            "properties": {
                "_links": {
                    "$ref": "#/definitions/handler.shipmentLinks"
                },
                "created_at": {
                    "type": "string"
                },
                "estimated_delivery": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "tracking_number": {
                    "type": "string"
                }
            }
        },
        "handler.dependencyStatus": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "handler.dimensionsRequest": {
            "type": "object",
            "required": [
                "height_cm",
                "length_cm",
                "width_cm"
            ],
            "properties": {
                "height_cm": {
                    "type": "number"
                },
                "length_cm": {
                    "type": "number"
                },
                "width_cm": {
                    "type": "number"
                }
            }
        },
        "handler.dimensionsResponse": {
            "type": "object",
            "properties": {
                "height_cm": {
                    "type": "number"
                },
                "length_cm": {
                    "type": "number"
                },
                "width_cm": {
                    "type": "number"
                }
            }
        },
        "handler.errorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "handler.getShipmentResponse": {
            "type": "object",
            "properties": {
                "_links": {
                    "$ref": "#/definitions/handler.shipmentLinks"
                },
                "created_at": {
                    "type": "string"
                },
                "destination": {
                    "$ref": "#/definitions/handler.addressResponse"
                },
                "estimated_delivery": {
                    "type": "string"
                },
                "origin": {
                    "$ref": "#/definitions/handler.addressResponse"
                },
                "package": {
                    "$ref": "#/definitions/handler.packageResponse"
                },
                "sender": {
                    "$ref": "#/definitions/handler.senderResponse"
                },
                "service_type": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "status_history": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.statusHistoryItemResponse"
                    }
                },
                "tracking_number": {
                    "type": "string"
                }
            }
        },
        "handler.listShipmentsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.shipmentSummaryResponse"
                    }
                },
                "pagination": {
                    "$ref": "#/definitions/handler.paginationResponse"
                }
            }
        },
        "handler.loginRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "handler.packageRequest": {
            "type": "object",
            "required": [
                "currency",
                "declared_value",
                "description",
                "dimensions",
                "weight_kg"
            ],
            "properties": {
                "currency": {
                    "type": "string"
                },
                "declared_value": {
                    "type": "number"
                },
                "description": {
                    "type": "string"
                },
                "dimensions": {
                    "$ref": "#/definitions/handler.dimensionsRequest"
                },
                "weight_kg": {
                    "type": "number"
                }
            }
        },
        "handler.packageResponse": {
            "type": "object",
            "properties": {
                "currency": {
                    "type": "string"
                },
                "declared_value": {
                    "type": "number"
                },
                "description": {
                    "type": "string"
                },
                "dimensions": {
                    "$ref": "#/definitions/handler.dimensionsResponse"
                },
                "weight_kg": {
                    "type": "number"
                }
            }
        },
        "handler.paginationResponse": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                }
            }
        },
        "handler.readinessResponse": {
            "type": "object",
            "properties": {
                "dependencies": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/handler.dependencyStatus"
                    }
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "handler.registerRequest": {
            "type": "object",
            "properties": {
                "client_id": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "handler.senderRequest": {
            "type": "object",
            "required": [
                "email",
                "name",
                "phone"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                }
            }
        },
        "handler.senderResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                }
            }
        },
        "handler.shipmentLinks": {
            "type": "object",
            "properties": {
                "events": {
                    "type": "string"
                },
                "self": {
                    "type": "string"
                }
            }
        },
        "handler.shipmentSummaryResponse": {
            "type": "object",
            "properties": {
                "_links": {
                    "$ref": "#/definitions/handler.shipmentLinks"
                },
                "created_at": {
                    "type": "string"
                },
                "destination": {
                    "$ref": "#/definitions/handler.addressResponse"
                },
                "estimated_delivery": {
                    "type": "string"
                },
                "origin": {
                    "$ref": "#/definitions/handler.addressResponse"
                },
                "sender": {
                    "$ref": "#/definitions/handler.senderResponse"
                },
                "service_type": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "tracking_number": {
                    "type": "string"
                }
            }
        },
        "handler.statusHistoryItemResponse": {
            "type": "object",
            "properties": {
                "notes": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "handler.userPayload": {
            "type": "object",
            "properties": {
                "client_id": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3000",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "99minutos Shipping Tracking API",
	Description:      "Event-driven shipment tracking system for 99minutos. Processes 10,000+ events/second with guaranteed per-shipment ordering.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
